### ISSUE TITLE
`playOnMount: false` plays on mount

### ISSUE THREAD

**Issue by alexcarpenter** [tol-is/use-scramble#5]
`playOnMount` doesn't seem to work as expected

https://codesandbox.io/p/sandbox/clever-wood-69lkq2?file=%2Fsrc%2FApp.js%3A7%2C16

**Comment by tol-is** [comment]
You're right @alexcarpenter, good shout, i'll try and fix it asap. Do you plan on using it for a/your website soon?

P.S. Nice personal website, i love it!

**Comment by alexcarpenter** [comment]
@tol-is no rush on my end, was just checking out the library.

**Comment by tol-is** [comment]
Fixed the `playOnMount` prop on `v2.2.13`.  

https://codesandbox.io/p/sandbox/clever-wood-forked-6hjr28

I appreciate the feedback!
