### ISSUE TITLE
`onAnimationEnd` does not fire on replays

### ISSUE THREAD

**Issue by alexcarpenter** [tol-is/use-scramble#6]
`onAnimationEnd` only fires on first animation play. Subsequent replays do no trigger the callback.

https://codesandbox.io/p/sandbox/clever-wood-69lkq2?file=%2Fsrc%2FApp.js%3A22%2C9

**Comment by tol-is** [comment]
@alexcarpenter Seems ok on the sandbox, but will double check to see if it gets flaky

**Comment by alexcarpenter** [comment]
Ah apologies, I thought I had seen it not firing on subsequent replays.
