### ISSUE TITLE
Question: How to disable initial scramble?

### ISSUE THREAD

**Issue by Kikobeats** [tol-is/use-scramble#7]
This hook is top, thanks for it!

Since I want to use this for links, I'm trying to don't show the initial scramble, just showing the neat effect on hover.

is it an easy way to achieve that? appreciated your help 🙏

**Comment by Kikobeats** [comment]
```
useScramble({ 
  playOnMount: false
});
```

<picture data-single-emoji=":facepalm:" title=":facepalm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/facepalm/04bb5b6ae709b8ae.png" alt=":facepalm:" align="absmiddle"></picture>

**Comment by tol-is** [comment]
Glad you got it figured easily @Kikobeats
